# Generated by Django 5.2.4 on 2026-04-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('grade', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('review', 'Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_description', models.TextField(blank=True)),
                ('original_description', models.TextField(blank=True)),
                ('weekly_objective', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_contents', to='projects.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='framework.session')),
            ],
            options={
                'ordering': ['session__number'],
                'unique_together': {('project', 'session')},
            },
        ),
    ]
