# Generated by Django 5.2.4 on 2026-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_sessionversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subject',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subject_track',
            field=models.CharField(choices=[('LL', 'Life Forms'), ('MM', 'Machines and Materials'), ('HS', 'Human Services')], default='LL', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_competency',
            field=models.CharField(choices=[('MSP15.C1', 'SP15 — Smart Systems & IoT: Foundational understanding'), ('MSP15.C2', 'SP15 — Smart Systems & IoT: IoT prototype building'), ('MSP15.C3', 'SP15 — Smart Systems & IoT: Iterative IoT solution'), ('MSP16.C1', 'SP16 — AI, Coding & Robotics: AI/ML concepts'), ('MSP16.C2', 'SP16 — AI, Coding & Robotics: Programming & algorithms'), ('MSP16.C3', 'SP16 — AI, Coding & Robotics: Functional automated systems'), ('MSP17.C1', 'SP17 — Design & Emerging Tech: Design principles'), ('MSP17.C2', 'SP17 — Design & Emerging Tech: Emerging tech prototypes'), ('MSP17.C3', 'SP17 — Design & Emerging Tech: Tech refinement')], default='MSP15.C1', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_competency_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessioncontent',
            name='weekly_brief',
            field=models.TextField(blank=True),
        ),
    ]
