# Generated by Django 5.2.4 on 2026-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_subject_project_description_and_more'),
    ]

    operations = [
        # Step 1: Convert existing string values to JSON arrays in-place
        migrations.RunSQL(
            sql="""
                UPDATE projects_project
                SET tech_competency = '["' || tech_competency || '"]'
                WHERE tech_competency NOT LIKE '[%';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Change field type to JSONField
        migrations.AlterField(
            model_name='project',
            name='tech_competency',
            field=models.JSONField(default=list),
        ),
    ]
