# Generated by Django 5.2.4 on 2026-05-05 09:49

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_alter_competency_options_and_more'),
        ('projects', '0004_tech_competency_to_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('challenge_card_content', models.JSONField(blank=True, default=dict)),
                ('lesson_plan_content', models.JSONField(blank=True, default=dict)),
                ('session1_ppt_content', models.JSONField(blank=True, default=dict)),
                ('session2_ppt_content', models.JSONField(blank=True, default=dict)),
                ('challenge_card_file', models.FileField(blank=True, null=True, upload_to=projects.models._materials_upload_path)),
                ('lesson_plan_file', models.FileField(blank=True, null=True, upload_to=projects.models._materials_upload_path)),
                ('session1_ppt_file', models.FileField(blank=True, null=True, upload_to=projects.models._materials_upload_path)),
                ('session2_ppt_file', models.FileField(blank=True, null=True, upload_to=projects.models._materials_upload_path)),
                ('ai_tokens_used', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_materials', to='projects.project')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='framework.week')),
            ],
            options={
                'verbose_name': 'Weekly Materials',
                'verbose_name_plural': 'Weekly Materials',
                'ordering': ['week__number'],
                'unique_together': {('project', 'week')},
            },
        ),
    ]
