# Generated by Django 5.2.4 on 2026-04-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('period_type', models.CharField(choices=[('block1', 'Block Period 1'), ('block2', 'Block Period 2'), ('reflection', 'Single Period: Reflection')], max_length=20)),
                ('challenge_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('generic_description', models.TextField()),
                ('weekly_objective_template', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('phase', models.CharField(max_length=50)),
                ('kaushal_bodh_questions', models.JSONField(default=list)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_code', models.CharField(max_length=10)),
                ('sp_name', models.CharField(max_length=200)),
                ('msp_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='framework.session')),
            ],
            options={
                'ordering': ['sp_code', 'msp_code'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='framework.week'),
        ),
    ]
