# Generated by Django 5.2.4 on 2026-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['track', 'sp_code', 'msp_code']},
        ),
        migrations.RemoveField(
            model_name='session',
            name='challenge_number',
        ),
        migrations.RemoveField(
            model_name='session',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='session',
            name='weekly_objective_template',
        ),
        migrations.AddField(
            model_name='competency',
            name='is_tech_slot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competency',
            name='track',
            field=models.CharField(choices=[('ALL', 'All Tracks'), ('LL', 'Life Forms'), ('MM', 'Machines and Materials'), ('HS', 'Human Services')], default='ALL', max_length=3),
        ),
    ]
