# Generated by Django 5.2.4 on 2026-04-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INIT', 'INIT'), ('RESOLVE', 'RESOLVE'), ('INJECT', 'INJECT'), ('STREAM', 'STREAM'), ('TOKEN', 'TOKEN'), ('SAVE', 'SAVE'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
