# Reference sample output — Human Services, Grade 8, Topic: Future Economy MarTech
# Tech Competency used: MSP15.C1 (Smart Systems and IoT)
# Fed into AI prompt as few-shot example to enforce output quality and format.

SAMPLE_OUTPUT = {
    'BP1': {
        'week_num': 1,
        'weekly_brief': 'Focus : By the end of this week, students will be able to deconstruct the relationship between personal identity and digital environments, identify the ethical implications of AI-driven marketing, and map their personal strengths to specific MarTech roles within the future economy.\n\nChallenge:\nThe Scenario: A new "Future Economy" startup, EcoPulse (which makes wearable tech that rewards users for low-carbon travel), is about to launch. However, their AI marketing tool has generated three different "user personas" that are full of cultural stereotypes and privacy risks.\n\nThe Task: In your project teams, you must act as MarTech Consultants to:\nAudit the Environment: Identify how EcoPulse ads might unfairly influence a teenager\'s "sense of self" or "identity" (referencing MSP1.C1).\nCultural Sensitivity Check: Find one element in their global campaign that fails to "appreciate cultural differences" and propose a respectful alternative (MSP13.C1).\nEthics Report: Flag one instance of "AI bias" or "misleading intent" in their digital content and explain how to fix it to be more ethical (MSP4.C4).\nThe Deliverable Worksheet: A Digital Audit worksheet at the end of Session 2.\n\nSummary for Students:\nWhat will I be able to do?       \nAnalyze how digital media tries to influence your identity, detect bias in AI and ads, and map your personal strengths to future-economy careers.\nWhat will I need?        \nA "critical lens" for viewing online content, an open mind for cross-cultural discussion, and your curiosity mapping tools.\nWhy is this relevant?        \nYour digital footprint is your future resume. Understanding the tech (MarTech) behind the screen gives you the power to control your digital world rather than being controlled by it.\n\nSuccess Criteria:\nSelf-Awareness: I can explain how digital environments (ads/feeds) influence my choices and sense of self.\nGlobal Mindset: I can identify a cultural stereotype or bias in a digital marketing campaign.\nFuture Readiness: I have identified a specific MarTech role (e.g., Data Ethicist, Strategist) that aligns with my personal strengths.',
        'session_breakdown': 'Block Period 1: Project Launch & Context Exploration\nTheme: The Invisible Hand – How MarTech Shapes Our World\nDuration: 80 Minutes\n\nI. The Hook: The "Filter Bubble" Experiment (15 mins)\nActivity: Show two vastly different ad feeds for the same product (e.g., a sustainable sneaker) targeted at two different personas \n\nDiscussion: How did the "environment" of these users change what they saw?\n\nCompetency Alignment: MSP1.C1 – Discuss how digital roles and environments influence our developing sense of self.\n\nII. The Story: The Future Economy & MarTech (20 mins)\nScenario: Introduce a real-world problem: A local sustainable brand is failing because they can’t reach people who care.\n\nConcept: Explain MarTech as the "Bridge" between a product and the person who needs it.\n\nWhy is this relevant? In a future economy, every job—from art to engineering—requires an understanding of how to communicate value through technology.\n\nIII. Careers & Roles: The MarTech Team (20 mins)\nConnecting with Jobs: Map the project to future careers:\nData Ethicist: Ensuring ads aren\'t biased (MSP4.C4).\nCultural Consultant: Adapting ideas for different communities (MSP13.C1).\nGrowth Strategist: Setting goals and monitoring progress (MSP2.C2).\n\nActivity: "Strength Mapping" (MSP14.C2). Students identify one personal interest (e.g., gaming, art, social justice) and find one MarTech role that fits.\n\nIV. Ethical Deep Dive: Intent & Bias (15 mins)\nActivity: Analyze "Dark Patterns" or AI-generated sponsored content.\n\nTask: Students identify one example of "intent" (is this trying to help me or just track me?) (MSP4.C4).\n\nV. Closing: Personal Aspirations (10 mins)\nReflection: What role in this "Future Economy" sounds most like you?',
    },
    'BP2': {
        'week_num': 1,
        'session_breakdown': 'Block Period 2: Understanding the Challenge & Curiosity Mapping\nTheme: Unpacking the MarTech Toolbox\nDuration: 80 Minutes\n\nI. Unpacking the Challenge (20 mins)\nThe Project Question: "How can we use Marketing Technology to ethically promote a future-economy solution while respecting cultural identities?"\nIdentify Key Ideas: Use a "Think-Pair-Share" to define "Future Economy" (Sustainable, Digital, Equitable) and "MarTech" (Data + Creativity).\n\nII. Case Study: The Global vs. Local Lens (20 mins)\nActivity: Compare two MarTech campaigns from different cultures (MSP13.C1).\nObservation: How do different communities value "privacy" or "social status"? Students document one similarity and one difference they appreciate.\n\nIII. Prior Knowledge & Curiosity Mapping (20 mins)\nThe "KWH" Chart:\n\nK (Know): What digital tools do I already use? (Instagram, AI, Spreadsheets).\nW (Want to Know): How does an algorithm actually "know" me? How do I build a professional digital footprint?\nH (How): What resources/experts do we need?\nMapping: Identifying areas of investigation like AI ethics or data visualization (MSP4.C4).\n\nIV. Goal Setting: Short-Term Sprint (15 mins)\nActivity: Students set a MSP2.C2 goal for the week (e.g., "By Friday, I will have researched three ethical AI marketing tools").\nStrategy: What "obstacles" (distraction, lack of info) might they face?\n\nV. Reflection & Investigation List (5 mins)\nTask: Finalize the "What will I need?" list. (e.g., Microcontrollers, data sets, design software).',
    },
    'BP3': {
        'week_num': 2,
        'weekly_brief': 'Focus : By the end of this week, students will demonstrate a foundational understanding of the MarTech industry by interpreting data patterns in advertising, identifying the integration of IoT/smart systems in marketing, and applying design principles to hypothesize future advertising trends and start exploring Marctech/ad creation digital tools to create marketing statergies and content. \n\nChallenge: The Marketing Landscape Chart\nThe Task: Conduct a "Synoptic Survey" of 20–25 diverse ads (from social media, physical billboards, or school posters).\nAnalyze: Categorize them by medium (Static vs. Digital/Smart).\nInterpret: Use data literacy to identify which ads use "Emotional Triggers" vs. "Data Triggers" (MSP4.C3).\nSafety First: Demonstrate how to present this data while anonymizing personal user information (MSP4.C3/Digital Safety).\n\nSummary for Students:\nWhat will I need to know? \nHow to read patterns in data annd core concpets in marketing. \nWhat do I have to do? \nAnalyse trends and ads to find out the makrting landscape and tool exploration.\nHow do I keep others safe? \nBy learning how to hide personal user details while still showing big-picture environmental trends     \n\nSuccess Criteria:\nStrategic Thinking: I can identify why a marketing campaign failed by looking at user data and emotional triggers.\nTool Knowledge :  I am aware of the foundations to use various martech tools to create marketing campaign \nOrganization: My team has a clear roadmap with deadlines and assigned roles for every member.',
        'session_breakdown': 'Block Period 3: The Ad Detective Agency\nTheme: Deconstructing the Invisible\nDuration: 80 Minutes\n\nI. The Hook: "Meet the Expert" (15 mins)\nActivity: Show a pre-recorded interview or a high-impact case study of a MarTech Architect (e.g., someone who designs interactive billboards or algorithm-driven social campaigns).\n\nDiscussion: Identify three "invisible" technologies the expert mentioned (e.g., geofencing, sentiment analysis, pixel tracking).\n\nSkill: Understanding the scale of the MarTech industry.\n\nII. Core Knowledge: Static vs. Smart (15 mins)\nDemonstration: Compare a 1950s print ad (Static) to a 2026 personalized AR ad (Smart).\n\nKey Concept: Introduce Data Triggers (weather, location, time) vs. Emotional Triggers (fear of missing out, nostalgia, joy).\n\nSafety Note: Discuss Anonymization. Why do we care about the trend (e.g., "Students like snacks") but protect the individual (e.g., "Sarah bought a candy bar")?\n\nIII. The Challenge Launch: Synoptic Survey (40 mins)\nActivity: Teams go on an "Ad Scavenger Hunt" around the school or on a curated digital platform to find 20–25 ads.\n\nThe Log: Using a shared spreadsheet (MSP4.C1), students categorize each ad:\n\nMedium: (Social Media, Billboard, Email, Poster).\n\nType: (Static vs. Digital/Interactive).\n\nTrigger: (What is the "hook"?).\n\nSkill: Data gathering and categorization (MSP4.C3).\n\nIV. Debrief: Sharing the Findings (10 mins)\nActivity: Teams share one "Anomaly"—an ad that felt totally out of place or failed to land. Why did the data logic fail?',
    },
    'BP4': {
        'week_num': 2,
        'session_breakdown': 'Block Period 4: Mapping the Landscape\nTheme: Patterns, Trends, and Design\nDuration: 80 Minutes\n\nI. Data Synthesis: Interpreting the Survey (25 mins)\nActivity: Teams analyze their spreadsheet from Period 3.\n\nInterpretation: Create a simple pivot table or tally to find the Pattern.\n\nExample: "80% of ads we saw were digital, and most used \'Urgency\' as an emotional trigger."\n\nCompetency: MSP4.C3 – Constructing narratives from data representations.\n\nII. Tool Exploration: The MarTech Toolkit (20 mins)\nActivity: "Tool Speed-Dating." Introduce 3-4 digital tools students might use (e.g., Canva for design, Google Sheets for data, or basic AR creators).\n\nTask: Assign team roles based on interests: The Data Scientist (Analysis), The Creative Director (Design), The Project Manager (Organization).\n\nIII. Creating the Landscape Chart (25 mins)\nActivity: Design a "Marketing Landscape Chart" using a digital tool (MSP4.C1).\n\nDesign Focus: Apply MSP17.C1.\n\nColor Theory: Use contrasting colors to show different ad categories.\n\nErgonomics: Ensure the most important trend is the first thing the eye sees.\n\nDigital Safety: Final check—ensure no peer names or private locations are visible in the datasets.\n\nIV. Planning the Roadmap (10 mins)\nActivity: Teams fill out their Project Roadmap.\n\nGoal: Set deadlines for the "Find" phase (Week 4) and ensure every role knows their commitment (MSP14.C1).',
    },
    'BP5': {
        'week_num': 3,
        'weekly_brief': 'Focus : By the end of this week, students will develop proficieny in using martech tools and will be able to analyze real-world MarTech case studies to evaluate effective marketing strategies and mediums and make suggestions in their marketing and advertisement. Paralley, students also apply emotional regulation techniques during collaborative tasks, and demonstrate organizational skills by setting project milestones and tracking team and personal progress.\nChallenge: Ad Maestro \nTask : Analyse an ad and rework it using a tool of your choice based on feedback on ethic, design principles etc. \nSummary for Students:\nWhat will I need to know? \nHow to work with various mactech tools\nWhat do I have to do? \nDemostrate tools proficiency by reowork on ad on any 1-2 forms of medium/software/tool\nHow do I keep others safe? \nBy learning how to protect others personal user details while advertising and influencing others\n     \nSuccess Criteria:\nStrategic Troubleshooter : I can identify why a marketing campaign failed and suggest changes to make it better\nTool Knowledge :  I use various meidum and tools to create the suggested changes based on my analysis.\nOrganization: My team has a clear roadmap with deadlines and assigned roles for every member.',
        'session_breakdown': 'Block Period 5: Case Study & Skill Practice (Ad Maestro)\nTheme: The Art of the Pivot\nDuration: 80 Minutes\n\nI. The Hook: "The Expert’s Failure" (10 mins)\nActivity: Showcase a famous "Marketing Fail" (e.g., an ad that was culturally tone-deaf or technically glitched).\n\nDiscussion: Why did it fail? Was it the Design (Color/Form), the Ethics (Privacy/Bias), or the Data (Wrong Audience)?\n\nSkill: Critical analysis of strategies.\n\nII. Skill Practice: Tool Deep-Dive (25 mins)\nActivity: "Software Speed-Run." Guided mini-tasks in chosen platforms (e.g., editing a graphic in Canva, setting up a data filter in a spreadsheet, or creating a 5-second AR trigger).\n\nCompetency: MSP4.C1 – Selecting and customizing digital tools for a specific audience.\n\nIII. Challenge: The Ad Maestro (35 mins)\nThe Task: Take an existing "Bad Ad" found in Week 2. Rework it to be "Better" (more ethical, better design, or smarter tech).\n\nRequirement: * Apply MSP17.C1 (Design Principles): Improve color contrast or layout ergonomics.\n\nApply MSP4.C3 (Data Logic): Suggest a specific "Smart Trigger" for this ad.\n\nSafety Check: Ensure the reworked ad doesn\'t use "dark patterns" (manipulative design) or expose user data.\n\nIV. Emotional Regulation: The "Pressure Valve" (10 mins)\nActivity: Mid-challenge, the teacher introduces a "technical glitch" (a simulated constraint). Students must stop and apply a regulation strategy (e.g., Square Breathing or a 1-minute team huddle).\n\nCompetency: MSP2.C1 – Developing awareness of emotional responses in challenging situations.',
    },
    'BP6': {
        'week_num': 3,
        'session_breakdown': 'Block Period 6: Knowledge Consolidation\nTheme: Roadmap to Success\nDuration: 80 Minutes\n\nI. Gallery Walk & Feedback (25 mins)\nActivity: Teams display their "Reworked Ads." Peers leave digital or physical comments focusing on: Strategic change, Design appeal, and Ethical safety.\n\nCompetency: MSP4.C3 – Using insights to construct explanations about real-world situations.\n\nII. Reflection: The Emotional Mirror (15 mins)\nActivity: Individual reflection in the "Growth Log."\n\nPrompt: "How did my thoughts influence my behavior when our team disagreed today? What strategy did I use to stay focused?"\n\nCompetency: MSP2.C1 – Understanding how emotions influence interactions.\n\nIII. Consolidation: MarTech Diagrams (20 mins)\nActivity: Students create a "Knowledge Map" (using a tool like Miro or a physical poster) connecting the tools they learned to the project challenge.\n\nSkill: Summarizing key learnings and connecting them to the "Find" phase next week.\n\nIV. Goal Setting & Milestones (20 mins)\nActivity: "The Sprint Planner." Teams define their short-term goals for the upcoming "Find" phase (Week 4).\n\nTask: Update the Project Roadmap with Milestones and Time-Tracking logs.\n\nCompetency: MSP14.C3 – Applying organization and decision-making skills to manage time and monitor progress.',
    },
    'BP7': {
        'week_num': 4,
        'weekly_brief': 'Focus : By the end of the week, students will be able to identify communication gaps between sustainable brands and their audiences, conduct user research to understand why certain messages fail to land, and frame a \'How Might We\' statement for an innovative MarTech solution\n\nChallenge: The MarTech Friction Audit\nThe Scenario: Many "Future Economy" solutions (e.g., local organic farms, solar startups, or ethical clothing) are failing—not because their product is bad, but because their advertising is invisible or mistrusted.\nThe Task: In project teams, students must:\nThe Ad-Audit: Identify a local "Future Economy" initiative and interview potential users to find out why they don\'t engage with it. (Is it lack of awareness? Poor digital trust? Boring ads?) (MSP11.C1).\nThe Data Vault: Categorize these "communication blockers" into a structured dataset (MSP4.C2).\nThe MarTech HMW: Synthesize findings into a problem statement: "How Might We use [Tech, e.g., AR/IoT/AI] to help [User] trust/discover [Sustainable Brand]?" (MSP12.C1).\n\nSummary for Students (Week 4)\nWhat will I be able to do?        \nConduct real research, organize data like a startup, and define a problem that people actually want solved.\nWhat will I need?       \nA notebook for interviews, an organized spreadsheet, and a practice of empathy.\nWhy is this relevant?        \nIn the Future Economy, the best entrepreneurs don\'t start with an idea; they start with a deep understanding of a person\'s problem.\n\nSuccess Criteria : \nEmpathy in Research: I have conducted an interview or observation that uncovered a real "pain point" in my community.\nData Organization: I have categorized my raw research notes into a structured and searchable dataset.\nProblem Framing: I have written a "How Might We" statement that is clear, ethical, and focused on a specific user need.',
        'session_breakdown': 'Block Period 7: Problem Exploration & User Research\nTheme: The Detective Mindset – Hunting for Friction\nDuration: 80 Minutes\n\nI. The Hook: The "Invisible" Hero (10 mins)\nActivity: Show two brands: a high-tech "Fast Fashion" brand and a local "Sustainable Upcycler." Ask: "Why does the local hero feel \'invisible\' compared to the global giant?"\n\nDiscussion: Introduce the concept of Communication Gaps (Awareness, Trust, or Engagement).\n\nII. Skill Build: Empathetic Interviewing (15 mins)\nConcept: How to interview without leading the user. Focus on MSP11.C1 (Empathy).\n\nPractice: A 5-minute "Speed Interview" session where partners practice asking: "When was the last time you bought something sustainable? What stopped you?"\n\nInclusion Lens: Discuss MSP13.C1—how different age groups or cultural backgrounds in school might perceive "Sustainability" differently.\n\nIII. The Ad-Audit: Field Research (40 mins)\nThe Task: Teams go "into the field" (school cafeteria, staff room, or digital student forums) to find a specific Future Economy initiative (e.g., school garden, e-waste bin, local farm).\n\nThe Research: Conduct 3 mini-interviews with potential users to find the Friction.\n\nIs it Awareness? ("I didn\'t know we had a garden.")\n\nIs it Trust? ("I don\'t think they actually recycle the bins.")\n\nIs it Boring? ("The posters are ugly.")\n\nSelf-Management: MSP14.C1 – Students work in groups with high autonomy, tracking their time and meeting commitments.\n\nIV. Closing: The Raw Data Download (15 mins)\nActivity: Teams return and share one "Surprising Frustration" they heard.\n\nSafety/Ethics Check: Discuss MSP4.C4—ensure no names are attached to quotes to protect student privacy.',
    },
    'BP8': {
        'week_num': 4,
        'session_breakdown': 'Block Period 8: Insights & Problem Framing\nTheme: From Chaos to a Clear Mission\nDuration: 80 Minutes\n\nI. The Data Vault: Structuring Insights (25 mins)\nActivity: Teams take their raw notes and organize them into a structured dataset (Spreadsheet or Digital Whiteboard).\n\nCategorization: Use MSP4.C2 to group insights into themes: Visual Appeal, Lack of Information, Distrust, or Inconvenience.\n\nCritical Filter: Apply MSP4.C4—evaluate if user complaints are based on credible info or bias/satire.\n\nII. Identifying the USP (Unique Selling Proposition) (15 mins)\nActivity: Identify the "Unmet Need." If everyone says the recycling bin is "hard to find," the USP of the MarTech solution must be Visibility/Navigation.\n\nSkill: MSP12.C1 – Validating that the problem is real and worth solving before building.\n\nIII. Framing the MarTech "How Might We" (30 mins)\nThe Task: Synthesize the research into one powerful sentence.\n\nThe Formula: "How Might We use [Tech: AR/IoT/AI] to help [User] discover/trust [Brand] so that [Impact]?"\n\nExample: "How Might We use IoT sensors to help students see real-time recycling impact so that they trust the school\'s sustainability system?"\n\nCritique: Teams swap HMW statements and check for clarity and focus.\n\nIV. Consolidation: The Project Roadmap Update (10 mins)\nActivity: Teams log their finalized HMW statement into their digital portfolio.\n\nPlanning: Briefly discuss what kind of "Create" tools they will need next week based on their chosen tech.',
    },
    'BP9': {
        'week_num': 5,
        'weekly_brief': 'Focus : By the end of this week, students will be able to apply divergent thinking to generate imaginative advertising solutions, evaluate ideas against financial and sustainability criteria, and construct a low-fidelity MarTech prototype (e.g., an AR ad mock-up or interactive campaign flow)\n\nChallenge: The Campaign v1.0\nThe Scenario: You have identified why people aren\'t engaging with a sustainable brand (Week 4). Now, you must design the "Innovative Ad" that breaks through the noise.\nThe Task: In project teams, students must:\n\nMarTech Storming: Generate 15+ ways to use tech (AR, IoT, AI, or Interactive Media) to make a boring sustainability message exciting (MSP11.C2).\n\nThe Filter: Select the top idea by scoring it against: Production Cost, User Ease, and SDG Impact (MSP13.C3/MSP6.C1).\n\nThe Build: Construct a low-fidelity mock-up (a digital wireframe of an ad or a physical model of a smart billboard) (MSP11.C3/MSP17.C2).\nPrototyping: I have built a low-fidelity model that clearly demonstrates the "core idea" of my solution.\n\nSummary for Students:\nWhat will I be able to do?\nBrainstorm like a creative director, pick the most profitable and ethical idea, and build your first physical or digital ad model.\nWhat will I need?\nYour "Friction Data" from Week 4, rapid prototyping materials, and an "Out-of-the-Box" mindset.\nWhy is this relevant?\nIn the Future Economy, an idea is only as good as your ability to show people how it grabs attention\n\nSuccess Criteria:\nCreativity: I can generate advertising ideas that use digital tools, camera, content, AR, IoT, or AI to make sustainability "cool" (MSP11.C2).\nCritical Selection: I can justify my chosen idea based on its cost, user ease, and SDG impact (MSP6.C1).\nPrototyping: I have built a low-fidelity model that clearly communicates my "Ad-Tech" concept (MSP11.C3).',
        'session_breakdown': 'In Week 5, we transition from the "Problem" to the "Solution." This week is about creative explosion and rapid filtering. Students will step into the shoes of a Creative Tech Agency, using high-volume ideation to ensure their advertising campaign isn\'t just "another poster," but a high-tech bridge to a sustainable future.\n\nWeek 5: Focus – Create I (Ideating the MarTech Solution)\nWeekly Objective\n"By the end of this week, students will be able to apply divergent thinking to generate imaginative advertising solutions, evaluate ideas against financial and sustainability criteria, and construct a low-fidelity MarTech prototype (e.g., an AR ad mock-up or interactive campaign flow)."\n\nBlock Period 9: Idea Generation\nTheme: The MarTech Idea Factory\nDuration: 80 Minutes\n\nI. The Hook: "The Reverse Ad-Blocker" (15 mins)\nActivity: Show a boring sustainability flyer (e.g., "Please Recycle").\n\nThe "Worst Possible Idea" Exercise: Teams have 3 minutes to think of the most expensive, annoying, and useless way to advertise this (e.g., "A plane that drops gold-plated flyers").\n\nThe Flip: Analyze the logic of the bad ideas to find hidden gems. If the bad idea was "too loud," perhaps the good idea is an "interactive sound-based ad."\n\nSkill: MSP11.C2 – Breaking cognitive bias through divergent thinking.\n\nII. The Success Matrix: Criteria for "Good" (15 mins)\nActivity: Students define what a "Good Solution" looks like in the MarTech world.\n\nThe Filter: Introduce the Triple-Threat Rubric:\n\nFinancial: Is it "Spend vs. Save" smart? (MSP6.C1).\n\nFeasibility: Can we actually make this with digital tools or IoT?\n\nGlobal Impact: Does it align with an SDG (e.g., SDG 12: Responsible Consumption)? (MSP13.C3).\n\nIII. MarTech Storming: Volume over Quality (30 mins)\nThe Task: Teams must generate 15+ ways to solve their Week 4 friction point.\n\nThe Tech Prompt: Must include at least one idea for each: AR (Content), AI (Personalization), and IoT (Physical Interaction).\n\nSkill: MSP11.C2 – Generating a high volume of technologically feasible solutions.\n\nIV. The Selection Pitch (20 mins)\nActivity: Each team picks their "Winner."\n\nJustification: Briefly present why this idea was chosen over the others using the Financial and SDG criteria.\n\nDigital Prep: Begin a spreadsheet to track the "Estimated Cost" of the prototype vs. the final product (MSP4.C1).',
    },
    'BP10': {
        'week_num': 5,
        'session_breakdown': 'Block Period 10: Prototype Development\nTheme: Building the "Proof of Concept"\nDuration: 80 Minutes\n\nI. The Build Brief: Low-Fi vs. High-Fi (10 mins)\nConcept: A prototype is a "model to learn from," not the finished product.\n\nVisual Ergonomics: Remind students of MSP17.C1—where will the user\'s eye go? If it\'s an AR ad, is it easy to hold the phone?\n\nII. The Maker Sprint (55 mins)\nActivity: Teams build their v1.0 Mock-up.\n\nDigital Path: Use tools like Figma or Canva to create the "Screen Flow" of an ad.\n\nPhysical Path: Use cardboard and craft materials to model a "Smart Billboard" or "Interactive Bin."\n\nTechnical Requirement: Must show the UI (User Interface). For example, a paper cutout of a phone showing where the AR button is.\n\nSkill: MSP11.C3 – Constructing a low-fidelity prototype (Innovation).\n\nIII. The 10-Second "User Test" (10 mins)\nActivity: Teams swap prototypes. A peer from another team looks at the model for 10 seconds.\n\nFeedback: The peer must answer: "What is this ad asking me to do?"\n\nCritique: If they can\'t answer, the team must simplify the design.\n\nIV. Iteration Log (5 mins)\nTask: Based on the 10-second test, students record one Significant Revision they will make next week (MSP11.C3).\n\nOrganization: Teams check their roadmap and confirm they are ready for "Tech Integration" in Week 6.',
    },
    'BP11': {
        'week_num': 6,
        'weekly_brief': 'Focus : By the end of this week, students will be able to integrate smart system logic (IoT) into their advertisingmock-up prototypes to improve efficiency while demostratibg sentivity and ethics and produce design documentation that justifies their technical and financial choices."\n\nChallenge: The Intelligent Ad\nThe Task: Add an "Information Loop" to your ad. How does it react to data? (e.g., The ad only lights up when someone walks by). Document the "how" and the "cost" of this tech.\n\nSummary for Students:\nWhat will I be able to do?        \nMake your ad "smart" using IoT logic and write a professional report explaining your budget and tech choices.\nWhat will I need?        \nYour v1.0 prototype and a "Logic Flow" mindset.\nWhy is this relevant?        \nReal MarTech doesn\'t just look good; it uses data to save energy and money.\n\nSuccess Criteria:\nSystems Logic: I can explain how my "Smart Ad" uses sensors to manage resources more efficiently (MSP15.C3).\nFinancial Literacy: I can justify the cost of my tech by showing the long-term "Value" it creates (MSP6.C1).\nDocumentation: I have a clear digital record of my design ideas and logic flow (MSP4.C1).',
        'session_breakdown': 'Block Period 10: [contd.] Prototype Development\nTheme: Building the "Proof of Concept"\nDuration: 80 Minutes\n\nI. The Build Brief: Low-Fi vs. High-Fi (10 mins)\nConcept: A prototype is a "model to learn from," not the finished product.\n\nVisual Ergonomics: Remind students of MSP17.C1—where will the user\'s eye go? If it\'s an AR ad, is it easy to hold the phone?\n\nII. The Maker Sprint (55 mins)\nActivity: Teams build their v1.0 Mock-up.\n\nDigital Path: Use tools like Figma or Canva to create the "Screen Flow" of an ad.\n\nPhysical Path: Use cardboard and craft materials to model a "Smart Billboard" or "Interactive Bin."\n\nTechnical Requirement: Must show the UI (User Interface). For example, a paper cutout of a phone showing where the AR button is.\n\nSkill: MSP11.C3 – Constructing a low-fidelity prototype (Innovation).\n\nIII. The 10-Second "User Test" (10 mins)\nActivity: Teams swap prototypes. A peer from another team looks at the model for 10 seconds.\n\nFeedback: The peer must answer: "What is this ad asking me to do?"\n\nCritique: If they can\'t answer, the team must simplify the design.\n\nIV. Iteration Log (5 mins)\nTask: Based on the 10-second test, students record one Significant Revision they will make next week (MSP11.C3).\n\nOrganization: Teams check their roadmap and confirm they are ready for "Tech Integration" in Week 6.',
    },
    'BP12': {
        'week_num': 6,
        'session_breakdown': 'Block Period 12: Design Documentation & Refinement\nTheme: The MarTech Architect\'s Portfolio\nDuration: 80 Minutes\n\nI. Final Iteration: User-Centricity (20 mins)\nActivity: Based on the Peer Review in Period 11, teams make one final "Significant Revision" to the prototype.\n\nDesign Focus: Apply MSP17.C1. Check the Ergonomics (Is it easy to use?) and Color Theory (Does it look trustworthy?).\n\nSkill: MSP17.C3 – Refining solutions based on iterative feedback.\n\nII. The Financial Justification (20 mins)\nActivity: The "Spend vs. Save" Report.\n\nTask: Use a spreadsheet (MSP4.C1) to list the tech "costs" (Sensors, Screens, Data).\n\nJustification: Write a 3-sentence defense: "We chose a motion sensor because it costs $10 but saves $50 in electricity per year."\n\nSkill: MSP6.C1 – Practicing financial decisions to justify personal/project spending.\n\nIII. Creating the Multi-Modal Portfolio (30 mins)\nActivity: Teams compile their "Design Documentation."\n\nRequirements: * A photo/video of the prototype.\n\nThe Logic Flowchart (The "How it works").\n\nThe SDG impact statement (The "Why it matters"). (MSP13.C3).\n\nSkill: MSP4.C1 – Applying digital tools to communicate project outcomes effectively.\n\nIV. Milestone Check & Next Steps (10 mins)\nActivity: Update the Project Roadmap (MSP14.C3).\n\nPlanning: Identify what is needed for the "Improve" phase (Week 7) where they will test their ad\'s persuasiveness.',
    },
    'BP13': {
        'week_num': 7,
        'weekly_brief': 'Focus : By the end of the week students share their marketing campaign and evaluate how effectively it captures audience by taking feedback and reflect on user experinces to make final refinement and imporvements to their idea. Students will be able to systematically test advertising prototypes, and evaluate ethical risks like data privacy\n\nWeekly Challenge: The Ethical Agency Audit\nThe Task: Test your ad on real people. Does it change their minds about the sustainable brand? Create a business model and an "Ethics Code" for your campaign.\n\nSummary for Students\nWhat will I be able to do?\nTest your ideas like a scientist, plan a business like a founder, and protect users like an ethicist.\nWhat will I need?External testers (peers) and a "Venture Canvas."\nWhy is this relevant?\nAdvertising only works if people trust it. You must prove your tech is both effective and ethical.\n\nSuccess Criteria : \nEvidence-Based Growth: I have used real feedback to make a "significant revision" to my ad (MSP11.C3).\nVenture Logic: I can explain how my MarTech idea creates value for the user and the community (MSP12.C2).\nRisk Awareness: I have identified a privacy or financial risk and proposed a "Plan B" (MSP12.C3).\nFinancial Priority: My budget distinguishes between essential tech and "nice-to-have" features (MSP6.C2).\nGlobal Empathy: My "Ethics Code" shows I understand how my ad affects the wider community (MSP13.C2).',
        'session_breakdown': 'Block Period 13: Prototype Testing & Impact Reflection\nTheme: The Truth Lab\nDuration: 80 Minutes\n\nI. The Hook: "The Trust Gap" (10 mins)\nActivity: Show an ad that uses "Dark Patterns" (e.g., a fake close button or hidden costs).\n\nDiscussion: Why does this destroy a brand? Introduce the Ethical Agency Audit.\n\nSkill: MSP12.C3 – Identifying ethical risks and future implications of ventures.\n\nII. The Scientific Test (35 mins)\nActivity: "The User Lab." Teams set up their prototypes at stations. Peers from other teams act as "External Testers."\n\nTask: Testers use the prototype while the "Founders" observe (without helping).\n\nData Collection: Founders record:\n\nEngagement: Did the user notice the "Smart" trigger?\n\nPersuasion: Did the ad make them want to support the sustainable brand?\n\nFriction: Where did the user look confused?\n\nSkill: MSP11.C3 – Systematically gathering and analyzing feedback.\n\nIII. Impact & Ethics Audit (25 mins)\nActivity: "The Global Consequence Map."\n\nTask: Reflect on the tech used. If your ad uses AI or IoT sensors:\n\nPrivacy: Where is the data stored? Is it anonymized? (MSP6.C4).\n\nEquity: Does this ad exclude people without smartphones? (MSP13.C2).\n\nOutput: Draft a 3-point "Ethics Code" for their campaign (e.g., "We never track individual names, only foot traffic").\n\nIV. Emotional Check-in: Coping with Feedback (10 mins)\nActivity: "The Critique Circle." If testers didn\'t like an idea, how did it feel?\n\nSkill: MSP2.C3 – Applying constructive coping strategies when facing collaborative pressure.',
    },
    'BP14': {
        'week_num': 7,
        'session_breakdown': 'Block Period 14: Iteration & Venture Modeling\nTheme: Building a Resilient Venture\nDuration: 80 Minutes\n\nI. Analysis of Limitations (15 mins)\nActivity: Teams look at the "Friction" points from Period 13 and categorize them into: Technical Glitches, Design Confusion, or Ethical Concerns.\n\nSkill: MSP1.C3 – Evaluating how their design choices interact with the social context of the users.\n\nII. The Final Pivot (25 mins)\nActivity: Refining the Prototype.\n\nTask: Use digital tools or physical adjustments to make one significant revision based on the feedback. (e.g., changing the color of a button for better visibility or adding a "Privacy Info" icon).\n\nSkill: MSP17.C3 – Applying tech tools to refine solutions.\n\nIII. The Venture Canvas (30 mins)\nActivity: Designing the Venture Model.\n\nTask: Fill out a "Mini-Business Model" explaining:\n\nValue Creation: How does this help the sustainable brand?\n\nResources: What tech/money is needed?\n\nBudgeting: Track costs vs. projected impact. Distinguish between "Needs" (the sensor) and "Wants" (expensive aesthetic lights).\n\nSkill: MSP12.C2 / MSP6.C2 – Justifying financial decisions and pricing logic.\n\nIV. Risk & Mitigation Plan (10 mins)\nActivity: Identify one major risk (e.g., "What if the sensor breaks?" or "What if people find the ad intrusive?").\n\nTask: Propose a "Savings Buffer" or a "Safety Measure" to fix it.\n\nSkill: MSP12.C3 / MSP6.C4 – Identifying protective measures and mitigation strategies.',
    },
    'BP15': {
        'week_num': 8,
        'weekly_brief': 'Focus : By the end of the week, students will develop a full-stack pitch to share their financially smart and ethically sound campaign, justifying their design decisions and resource allocation to a panel of stakeholders\n\nChallenge: The Demo Day\nThe Task: Present your MarTech Venture. You must prove your ad is innovative, financially smart, and ethically sound to a panel of "Investors."\n\nSummary for Students\nWhat will I be able to do?        \nPitch an idea like a pro and defend your tech choices with data.\nWhat will I need?        \nYour final pitch deck and your prototype.\nWhy is this relevant?        \nIn the Future Economy, being able to communicate your value is as important as the tech itself.\n\nSuccess Crittiera: \nCommunication: I have delivered a multi-modal pitch that justifies my solution to stakeholders (MSP12.C4).\nFinancial Ethics: I can explain why my budget and resource use are responsible and fair (MSP6.C3).\nHistorical Awareness: I can explain how my innovation connects to the progress of civilization (MSP11.C4).',
        'session_breakdown': 'Block Period 15: Preparing the Showcase\nTheme: The Art of the Pitch\nDuration: 80 Minutes\n\nI. The Hook: "Value Beyond the Price Tag" (10 mins)\nActivity: Show a successful tech pitch (e.g., a "Shark Tank" highlight). Ask: "Did they just sell a gadget, or did they sell a solution to a human problem?"\n\nDiscussion: Introduce MSP6.C3—explain that the money they are asking for represents the value of their work, skills, and the resources they’ve managed.\n\nII. Pitch Deck Construction (40 mins)\nActivity: Using a digital template (Canva, Slides, etc.), teams build their "Full-Stack" pitch.\n\nRequirements (MSP4.C1):\n\nThe Problem: The Week 4 "Friction" findings.\n\nThe Innovation: A visual demonstration of the "Smart System" (Week 6).\n\nThe Venture Logic: How the business captures value (MSP12.C2).\n\nThe Ethical Code: How they protect user data and ensure fairness.\n\nVisual Check: Ensure the deck follows design principles (minimal text, high-impact visuals) to communicate effectively to an audience.\n\nIII. Financial Responsibility Check (15 mins)\nActivity: The "Fairness Audit."\n\nTask: Students review their budget. They must be prepared to answer: "Is your pricing fair? Are you paying for high-quality, ethical resources, or just the cheapest option?"\n\nSkill: MSP6.C3 – Reflecting on ethics and responsibility in financial interactions.\n\nIV. The Civilization Connection (15 mins)\nActivity: "The Innovation Timeline."\n\nTask: Add a slide or speaking point that connects their ad to the history of progress. Example: "In the past, we had town criers; then we had static posters; now, our IoT ad brings information directly to the people who need it most."\n\nSkill: MSP11.C4 – Appreciating design thinking as a tool for civilizational progress.',
    },
    'BP16': {
        'week_num': 8,
        'session_breakdown': 'Block Period 16: The Pitch / Showcase\nTheme: The MarTech Summit\nDuration: 80 Minutes\n\nI. The Setup (10 mins)\nActivity: Teams set up their prototypes and test their digital presentations.\n\nFinal Check: Ensure "Team Roles" are clear—who is the Lead Presenter? Who handles the Tech Demo? Who answers the Financial questions?\n\nII. The "Demo Day" Pitches (55 mins)\nThe Format: Each team has 5 minutes to pitch, followed by 3 minutes of Q&A from "Investors" (Peers/Teachers/Guests).\n\nThe Stakeholder Question: Investors must ask at least one question about Sustainability or Financial Ethics.\n\nSkill: MSP12.C4 – Presenting and justifying a comprehensive pitch to stakeholders.\n\nIII. Peer Review: Learning from Others (10 mins)\nActivity: "The Investor\'s Choice." Each student is given "Virtual Currency." They must "invest" in the team (other than their own) that showed the best balance of:\n\nInnovation (Tech)\n\nLogic (Data)\n\nResponsibility (Ethics/Money)\n\nIV. Closing Reflection (5 mins)\nActivity: One-word check-in: "How has your perspective on advertising changed since Week 1?"\n\nSkill: MSP11.C4 – Developing a critical lens on the impact of innovation.',
    },
    'BP17': {
        'week_num': 9,
        'weekly_brief': 'Focus : By the end of this week, students will be able to synthesize their project experiences to identify personal strengths and values, map their demonstrated skills to future-economy career roles, and evaluate how their personal identity influenced their academic and collaborative choices.\n\nChallenge:The Future Professional Blueprint\nThe Task: Complete the "Think & Answer" assessment. Match your favorite project tasks to a real 2030 job title.\n\nSummary for Students (Week 9)\nWhat will I be able to do?\nTranslate your project work into a resume of the future and understand your "Superpowers."\nWhat will I need?\nYour "Think & Answer" sheet and a moment of honest reflection.\nWhy is this relevant?The best entrepreneurs know their own strengths better than anyone else.\n\nSuccess Critieria: \nMetacognition: I can describe how my personal values guided my choices during the project (MSP1.C2).\nCareer Mapping: I have matched my project skills to a specific career role in the 2030 economy (MSP14.C2).\nIdentity Reflection: I can evaluate how my own identity interacted with my academic work (MSP1.C3).',
        'session_breakdown': 'Block Period 17: Consolidation & Personal Mapping\nTheme: The Person Behind the Project\nDuration: 80 Minutes\nI.The Hook: "The 2030 Resume" \n(10 mins)Activity: Show three job titles that didn\'t exist 10 years ago (e.g., Metaverse Architect, AI Ethicist, Sustainable Growth Hacker).\nDiscussion: "Which of these jobs requires the skills you used in Week 6 or Week 7?"\n\nII. Class Discussion: "Think & Answer" \nConsolidation (20 mins)Activity: A facilitated Socratic circle.\nPrompts for Discussion:\n"When did you feel most \'in the zone\'—researching the problem, designing the ad, or coding the logic?" (MSP14.C2)\n"How did your team handle the \'Week 7 Stress\'?\n Did your personal values (like honesty or persistence) help or hinder the process?" (MSP1.C2)\nSkill: MSP1.C3 – Evaluating how identity and emotions interact with social and academic contexts.\n\nIII. Individual Reflection: The Strength Audit (25 mins)\nTask: Students complete the "Think & Answer" Assessment Sheet.\nReflection Components:Task Analysis: List 3 specific tasks you performed. Which felt like a "Superpower"? Which felt like a "Drain"?\nValues Mapping: Identify a moment you had to make a choice (e.g., choosing a cheaper sensor vs. a more ethical one). What value guided that choice? (MSP1.C2)\nIdentity & Background: How did your personal background influence the "Sustainable Brand" you chose in Week 4? (MSP1.C3)\n\nIV. Career Mapping: Bridging to 2030 (15 mins)\nActivity: "The Career Matchmaker."\nThe Task: Based on their favorite project phase, students must pick a real or emerging job title:Liked the Research?-> User Experience (UX) Researcher.\nLiked the IoT/Logic?-> Smart Systems Engineer.\nLiked the Pitch/Venture?-. MarTech Strategist / Founder.\nSkill: MSP14.C2 – Connecting strengths and preferred ways of working to future roles.\n\nV. Closing: The Future Aspiration Statement (10 mins)\nActivity: Students write a "Letter to my Future Self" (1-2 sentences).\nPrompt: "In this project, I discovered that I am a [Strength] person who values [Value].\n In 2030, I want to use these to [Goal]."\nSubmission: Hand in the "Think & Answer" sheet and the Growth Portfolio.',
    },
    'BP18': {
        'week_num': 9,
        'session_breakdown': 'Buffer',
    },
}